# Generated by Django 5.1.3 on 2024-11-13 00:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('customers', '0001_initial'),
        ('parking', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='ParkingReservation',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('start_timestamp', models.DateTimeField()),
                ('duration_in_minutes', models.IntegerField()),
                ('booking_date', models.DateField()),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customers.customer')),
                ('parking_slot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='parking.parkingslot')),
            ],
        ),
        migrations.CreateModel(
            name='ParkingSlip',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('issue_date', models.DateField()),
                ('entry_time', models.DateTimeField()),
                ('exit_time', models.DateTimeField(blank=True, null=True)),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('reservation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reservations.parkingreservation')),
            ],
        ),
    ]
